app <- ShinyDriver$new("../../", loadTimeout=100000)
app$snapshotInit("BackOutCounties")

app$setInputs(stateChoices = c("MA", "ME"))
app$setInputs(mainTabsetPanel = "New Cases")
app$snapshot()
app$setInputs(chooseCounty = TRUE, wait_ = FALSE, values_ = FALSE)
app$snapshot()
app$setInputs(countyChoices = character(0), wait_ = FALSE, values_ = FALSE)
app$snapshot()
app$setInputs(countyChoices = "Barnstable")
app$snapshot()
app$setInputs(movingAvg = FALSE)
app$snapshot()
app$setInputs(chooseCounty = FALSE)
app$snapshot()
