app <- ShinyDriver$new("../../", loadTimeout = 100000)
app$snapshotInit("errorsOct11")

app$setInputs(movingAvg = FALSE, wait_ = FALSE, values_ = FALSE)
app$setInputs(mainTabsetPanel = "New Cases")
app$setInputs(newCaseTabsetPanel = "Data")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Cases")
app$setInputs(totalCaseTabsetPanel = "Data")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Deaths")
app$setInputs(newDeathsTabsetPanel = "Data")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Deaths")
app$setInputs(newDeathsTabsetPanel = "Data", timeout_ = 6000)
app$snapshot()
