app <- ShinyDriver$new("../../", loadTimeout = 100000)
app$snapshotInit("errorsOct11")

app$setInputs(movingAvg = FALSE, wait_ = FALSE, values_ = FALSE)
app$setInputs(mainTabsetPanel = "New Cases")
app$setInputs(newCaseTabsetPanel = "Data", wait_ = FALSE, values_ = FALSE)
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Cases")
app$setInputs(totalCaseTabsetPanel = "Data", wait_ = FALSE, values_ = FALSE)
app$snapshot()
app$setInputs(mainTabsetPanel = "New Deaths")
app$setInputs(newDeathsTabsetPanel = "Data", wait_ = FALSE, values_ = FALSE)
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Deaths")
app$setInputs(newDeathsTabsetPanel = "Data", wait_ = FALSE, values_ = FALSE)
app$snapshot()
