app <- ShinyDriver$new("../../", loadTimeout = 100000)
app$snapshotInit("testResultsTabTest")

app$setInputs(mainTabsetPanel = "Test Positivity")
app$snapshot()
app$setInputs(testResultsTabsetPanel = "Trend Line")
app$snapshot()
app$setInputs(testResultsTabsetPanel = "Data")
app$snapshot()
app$setInputs(movingAvg = FALSE)
app$snapshot()
app$setInputs(testResultsTabsetPanel = "Trend Line")
app$snapshot()
app$setInputs(testResultsTabsetPanel = "Boxplot")
app$snapshot()
app$setInputs(stateChoices = c("MA", "ME"))
app$snapshot()
app$setInputs(testResultsTabsetPanel = "Trend Line")
app$snapshot()
app$setInputs(testResultsTabsetPanel = "Data")
app$snapshot()
app$setInputs(movingAvg = TRUE)
app$snapshot()
app$setInputs(testResultsTabsetPanel = "Trend Line")
app$snapshot()
app$setInputs(testResultsTabsetPanel = "Boxplot")
app$snapshot()
app$setInputs(chooseCounty = TRUE, timeout_ = 4000)
app$setInputs(countyChoices = c("Barnstable", "Dukes", "Suffolk", "Worcester"))
app$snapshot()
app$setInputs(testResultsTabsetPanel = "Trend Line")
app$snapshot()
app$setInputs(testResultsTabsetPanel = "Data")
app$snapshot()
app$setInputs(movingAvg = FALSE, timeout_ = 4000)
app$snapshot()
app$setInputs(testResultsTabsetPanel = "Trend Line")
app$snapshot()
app$setInputs(testResultsTabsetPanel = "Boxplot")
app$snapshot()
