app <- ShinyDriver$new("../../", loadTimeout=100000)
app$snapshotInit("mytest")

Sys.sleep(7)
# app$setInputs(stateChoices = character(0))
app$setInputs(movingAvg = FALSE)
app$snapshot()
app$setInputs(mainTabsetPanel = "New Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "Test Growth")
app$snapshot()
app$setInputs(mainTabsetPanel = "Test Results")
app$snapshot()
app$setInputs(mainTabsetPanel = "Summary")
app$snapshot()
app$setInputs(movingAvg = TRUE)
app$setInputs(mainTabsetPanel = "Test Results")
app$snapshot()
app$setInputs(mainTabsetPanel = "Test Growth")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "Vaccination Progress")
app$snapshot()
app$setInputs(movingAvg = FALSE)
app$setInputs(stateChoices = c("MA", "ME"))
app$snapshot()
app$setInputs(mainTabsetPanel = "New Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "Test Growth")
app$snapshot()
app$setInputs(mainTabsetPanel = "Test Results")
app$snapshot()
app$setInputs(movingAvg = TRUE)
app$snapshot()
app$setInputs(mainTabsetPanel = "Test Growth")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "Vaccination Progress")
app$snapshot()
app$setInputs(movingAvg = FALSE)
app$setInputs(countyChoices = c("Barnstable", "Dukes", "Suffolk", "Worcester"),
              allowInputNoBinding_ = TRUE)
app$setInputs(mainTabsetPanel = "New Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Deaths")
app$snapshot()
app$setInputs(movingAvg = TRUE)
app$snapshot()
app$setInputs(mainTabsetPanel = "New Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Cases")
app$snapshot()
