app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(stateChoices = "MA")
app$setInputs(stateChoices = character(0))
app$setInputs(movingAvg = FALSE)
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$setInputs(movingAvg = TRUE)
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$setInputs(movingAvg = FALSE)
app$setInputs(stateChoices = "MA")
app$setInputs(stateChoices = c("MA", "ME"))
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$setInputs(movingAvg = TRUE)
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$setInputs(movingAvg = FALSE)
app$setInputs(countyChoices = "Barnstable")
app$setInputs(countyChoices = c("Barnstable", "Dukes"))
app$setInputs(countyChoices = c("Barnstable", "Dukes", "Suffolk"))
app$setInputs(countyChoices = c("Barnstable", "Dukes", "Suffolk", "Worcester"))
app$snapshot()
app$snapshot()
app$snapshot()
app$setInputs(movingAvg = TRUE)
app$snapshot()
app$snapshot()
