app <- ShinyDriver$new("../../", loadTimeout=100000)
app$snapshotInit("mytest")

Sys.sleep(7)
app$snapshot() # 1
app$setInputs(mainTabsetPanel = "New Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Deaths")
app$snapshot() # 5
app$setInputs(mainTabsetPanel = "Test Growth")
app$snapshot()
app$setInputs(mainTabsetPanel = "Test Results")
app$snapshot()
app$setInputs(mainTabsetPanel = "Summary")
app$snapshot()
app$setInputs(movingAvg = FALSE, wait_ = FALSE, values_ = FALSE)
app$setInputs(mainTabsetPanel = "Test Results")
app$snapshot()
app$setInputs(mainTabsetPanel = "Test Growth")
app$snapshot() # 10
app$setInputs(mainTabsetPanel = "Total Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Cases")
app$snapshot()
app$setInputs(stateChoices = c("MA", "ME"))
app$setInputs(mainTabsetPanel = "Vaccination Progress")
app$snapshot() # 15
app$setInputs(mainTabsetPanel = "New Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "Test Growth")
app$snapshot()
app$setInputs(mainTabsetPanel = "Test Results")
app$snapshot()
app$setInputs(movingAvg = TRUE)
app$setInputs(mainTabsetPanel = "Test Growth")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "Vaccination Progress")
app$snapshot()
app$setInputs(chooseCounty = TRUE)
app$setInputs(countyChoices = c("Barnstable", "Dukes", "Suffolk", "Worcester"))
app$setInputs(mainTabsetPanel = "New Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Deaths")
app$snapshot()
app$setInputs(movingAvg = FALSE)
app$snapshot()
app$setInputs(mainTabsetPanel = "New Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Cases")
app$snapshot()
app$setInputs(chooseCounty = FALSE)
Sys.sleep(2)
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Deaths")
app$snapshot()
