app <- ShinyDriver$new("../../", loadTimeout=100000)
app$snapshotInit("totalDeathsTest")

app$setInputs(mainTabsetPanel = "Total Deaths")
app$snapshot()
app$setInputs(movingAvg = FALSE)
app$snapshot()
app$setInputs(stateChoices = c("MA", "ME"), wait_ = FALSE, values_ = FALSE)
app$snapshot()
app$setInputs(movingAvg = TRUE)
app$snapshot()
app$setInputs(chooseCounty = TRUE)
app$setInputs(countyChoices = c("Barnstable", "Dukes", "Suffolk", "Worcester"))
app$snapshot()
app$setInputs(movingAvg = FALSE)
app$snapshot()
app$setInputs(countyChoices = character(0), wait_ = FALSE, values_ = FALSE)
app$setInputs(chooseCounty = FALSE)
app$snapshot()
