app <- ShinyDriver$new("../../", loadTimeout=100000)
app$snapshotInit("totalCasesTest")

app$setInputs(mainTabsetPanel = "Total Cases")
app$snapshot()
app$setInputs(movingAvg = FALSE)
app$snapshot()
app$setInputs(stateChoices = c("MA", "ME"))
app$snapshot()
app$setInputs(movingAvg = TRUE)
app$snapshot()
app$setInputs(chooseCounty = TRUE)
app$setInputs(countyChoices = character(0))
app$setInputs(countyChoices = c("Barnstable", "Dukes", "Suffolk", "Worcester"))
app$snapshot()
app$setInputs(movingAvg = FALSE)
app$snapshot()
app$setInputs(countyChoices = character(0))
app$setInputs(chooseCounty = FALSE)
app$snapshot()
