app <- ShinyDriver$new("../../")
app$snapshotInit("updateTables")

app$setInputs(movingAvg = FALSE)
app$setInputs(vaccinationTabsetPanel = "Data")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Cases")
app$setInputs(newCaseTabsetPanel = "Data")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Cases")
app$setInputs(totalCaseTabsetPanel = "Data")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Deaths")
app$setInputs(newDeathsTabsetPanel = "Data")
app$setInputs(mainTabsetPanel = "Total Deaths")
app$setInputs(totalDeathsTabsetPanel = "Data")
app$snapshot()
app$setInputs(mainTabsetPanel = "Testing Rate")
app$setInputs(testGrowthTabsetPanel = "Data")
app$snapshot()
app$setInputs(mainTabsetPanel = "Test Positivity")
app$setInputs(testPositivityTabsetPanel = "Data")
app$snapshot()
app$setInputs(stateChoices = c("DE", "OH"))
app$snapshot()
app$setInputs(mainTabsetPanel = "Testing Rate")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Deaths")
app$snapshot()
app$setInputs(mainTabsetPanel = "Total Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "New Cases")
app$snapshot()
app$setInputs(mainTabsetPanel = "Vaccination Progress")
app$snapshot()
